### ISSUE TITLE
Please set correct IP

### ISSUE THREAD

**Issue by extsoft** [pospravahatqc/pybc#1]
See more details in https://gist.github.com/extsoft/bf1b9884cbaccf1eb2efd0330ae542c7#1-vagrant.

https://github.com/pospravahatqc/pybc/blob/7d23ff7f725076b6787cd62416b078ce96ecdcae/Vagrantfile#L36

**Comment by pospravahatqc** [comment]
Fixed by day#4 commit

**Comment by pospravahatqc** [comment]
Fixed by day#4 commit
