### ISSUE TITLE
Incorrect gitignore format

### ISSUE THREAD

**Issue by extsoft** [pospravahatqc/pybc#6]
https://github.com/pospravahatqc/pybc/blob/aa3e09164875fecbef0c9eeff02fb25f2a29c91f/.gitignore#L3

Please remove `/` before the folder name (`/.vagrant/` has to be `.vagrant/`). `/` in the beginning, means from the root of a disk.

Also, please remove `.vagrant/` from git.

**Comment by pospravahatqc** [comment]
log decorator --> func names + args decorator
