### ISSUE TITLE
Log message is incorrect

### ISSUE THREAD

**Issue by extsoft** [pospravahatqc/pybc#7]
https://github.com/pospravahatqc/pybc/blob/aa3e09164875fecbef0c9eeff02fb25f2a29c91f/app_code/decorator_app.py#L4

Visit https://gist.github.com/extsoft/f9963e86d9162604fe2d012b0653d7d0#5-decorator to get more details.

**Comment by pospravahatqc** [comment]
Fixed by # log decorator --> func names + args decorator
